# Generated by Django 5.0.3 on 2024-03-23 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35, verbose_name='Nome')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
            ],
        ),
        migrations.AlterField(
            model_name='produtor',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='produtor',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='produtor',
            name='senha',
            field=models.CharField(max_length=20, verbose_name='Senha'),
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereco')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Longitude')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cidade')),
                ('produtor', models.ManyToManyField(to='core.produtor')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brinco', models.CharField(max_length=6, verbose_name='Brinco')),
                ('dataNascimento', models.DateField(verbose_name='Data de nascimento')),
                ('sexo', models.CharField(max_length=5, verbose_name='Sexo')),
                ('racaObservacao', models.CharField(max_length=50, verbose_name='Raça de observação')),
                ('racaPredominante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.raca')),
            ],
        ),
    ]
